# name: Deploy to Home Server

# on:
#   push:
#     branches: [ main ]

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v3

#       - name: Deploy via SSH
#         uses: appleboy/ssh-action@v1.0.0
#         with:
#           host: ${{ secrets.SERVER_HOST }}
#           username: ${{ secrets.SERVER_USER }}
#           key: ${{ secrets.DEPLOY_KEY }}
#           script: |
#             cd ${{ secrets.SERVER_PATH }}
#             git pull origin main
#             sudo chown -R www-data:www-data .
